// ── Indian States ────────────────────────────────────────────────────
export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

// ── Common Commodities ──────────────────────────────────────────────
export const COMMODITIES = [
  "Rice",
  "Wheat",
  "Maize",
  "Bajra",
  "Jowar",
  "Barley",
  "Ragi",
  "Potato",
  "Onion",
  "Tomato",
  "Soyabean",
  "Groundnut",
  "Mustard",
  "Cotton",
  "Sugarcane",
  "Turmeric",
  "Chilli Red",
  "Green Chilli",
  "Brinjal",
  "Cauliflower",
  "Cabbage",
  "Lady Finger",
  "Banana",
  "Mango",
  "Apple",
  "Garlic",
  "Ginger",
  "Coriander",
  "Lemon",
  "Capsicum",
];

// ── Hindi Labels (Bilingual Support) ────────────────────────────────
export const LABELS = {
  en: {
    appTitle: "Crop Logistics Optimizer",
    appSubtitle: "Find the best mandi for your crop",
    // Form
    step1Title: "Your Location",
    step1Subtitle: "Where are you?",
    step2Title: "Crop Details",
    step2Subtitle: "What are you selling?",
    step3Title: "Logistics",
    step3Subtitle: "Transport & Storage",
    village: "Village",
    villagePlaceholder: "e.g. Rampur",
    district: "District",
    districtPlaceholder: "e.g. Varanasi",
    state: "State",
    statePlaceholder: "Select your state",
    commodity: "Commodity",
    commodityPlaceholder: "Select your crop",
    cropQuality: "Crop Quality",
    qualityLow: "Low",
    qualityMedium: "Medium",
    qualityHigh: "High",
    quantity: "Quantity (Quintals)",
    quantityPlaceholder: "e.g. 10",
    transportAvailability: "Transport Available?",
    storageAvailability: "Storage Available?",
    maxRadius: "Search Radius",
    yes: "Yes",
    no: "No",
    next: "Next",
    back: "Back",
    findMandi: "Find Best Mandi",
    // Loading
    loading: "Finding best mandi for you...",
    loadingSubtext: "Analyzing prices, distance & transport costs",
    // Results
    bestChoice: "Best Choice",
    highProfit: "High Profit",
    lowDistance: "Low Distance",
    topRecommendation: "Top Recommendation",
    allMandis: "All Mandis",
    mandiName: "Mandi",
    distance: "Distance",
    modalPrice: "Price",
    transportCost: "Transport Cost",
    netProfit: "Net Profit",
    dpsScore: "DPS Score",
    decision: "Decision",
    transportNow: "Transport Now",
    delayShipment: "Delay Shipment",
    sortBy: "Sort by",
    profit: "Profit",
    confirmSelection: "Confirm Selection",
    confirmed: "Selection Confirmed!",
    noMandis: "No nearby mandis found",
    noMandisHint: "Try increasing the search radius",
    tryAgain: "Try Again",
    newSearch: "New Search",
    whyThisMandi: "Why this mandi?",
    whyExplanation:
      "This mandi has the best combination of price, distance, and transport cost for your crop.",
    km: "km",
    perQuintal: "/qtl",
    // Map
    farmerLocation: "Your Location",
    mapTitle: "Mandis on Map",
  },
  hi: {
    appTitle: "फसल लॉजिस्टिक्स ऑप्टिमाइज़र",
    appSubtitle: "अपनी फसल के लिए सबसे अच्छी मंडी खोजें",
    // Form
    step1Title: "आपका स्थान",
    step1Subtitle: "आप कहाँ हैं?",
    step2Title: "फसल विवरण",
    step2Subtitle: "आप क्या बेच रहे हैं?",
    step3Title: "परिवहन",
    step3Subtitle: "ट्रांसपोर्ट और स्टोरेज",
    village: "गाँव",
    villagePlaceholder: "जैसे: रामपुर",
    district: "जिला",
    districtPlaceholder: "जैसे: वाराणसी",
    state: "राज्य",
    statePlaceholder: "अपना राज्य चुनें",
    commodity: "फसल",
    commodityPlaceholder: "अपनी फसल चुनें",
    cropQuality: "फसल की गुणवत्ता",
    qualityLow: "कम",
    qualityMedium: "मध्यम",
    qualityHigh: "अच्छी",
    quantity: "मात्रा (क्विंटल)",
    quantityPlaceholder: "जैसे: 10",
    transportAvailability: "ट्रांसपोर्ट उपलब्ध?",
    storageAvailability: "स्टोरेज उपलब्ध?",
    maxRadius: "खोज दूरी",
    yes: "हाँ",
    no: "नहीं",
    next: "आगे",
    back: "पीछे",
    findMandi: "सबसे अच्छी मंडी खोजें",
    // Loading
    loading: "आपके लिए सबसे अच्छी मंडी खोज रहे हैं...",
    loadingSubtext: "कीमतें, दूरी और परिवहन लागत का विश्लेषण",
    // Results
    bestChoice: "सबसे अच्छा",
    highProfit: "ज़्यादा मुनाफ़ा",
    lowDistance: "कम दूरी",
    topRecommendation: "शीर्ष सिफारिश",
    allMandis: "सभी मंडियाँ",
    mandiName: "मंडी",
    distance: "दूरी",
    modalPrice: "भाव",
    transportCost: "ट्रांसपोर्ट खर्च",
    netProfit: "शुद्ध मुनाफ़ा",
    dpsScore: "DPS स्कोर",
    decision: "सुझाव",
    transportNow: "अभी भेजें",
    delayShipment: "बाद में भेजें",
    sortBy: "क्रम",
    profit: "मुनाफ़ा",
    confirmSelection: "चयन पक्का करें",
    confirmed: "चयन पक्का हो गया!",
    noMandis: "पास में कोई मंडी नहीं मिली",
    noMandisHint: "खोज दूरी बढ़ाकर देखें",
    tryAgain: "फिर से कोशिश करें",
    newSearch: "नई खोज",
    whyThisMandi: "यह मंडी क्यों?",
    whyExplanation:
      "इस मंडी में आपकी फसल के लिए कीमत, दूरी और ट्रांसपोर्ट खर्च का सबसे अच्छा संयोजन है।",
    km: "किमी",
    perQuintal: "/क्विंटल",
    // Map
    farmerLocation: "आपका स्थान",
    mapTitle: "मंडियाँ मैप पर",
  },
};

// ── Profit Thresholds (for color coding) ────────────────────────────
export const PROFIT_THRESHOLDS = {
  high: 5000, // ₹5000+ net profit → green
  medium: 2000, // ₹2000-5000 → yellow
  // Below ₹2000 → red
};

// ── Quality Map ─────────────────────────────────────────────────────
export const QUALITY_MAP = {
  0: { value: 30, label: "Low" },
  1: { value: 60, label: "Medium" },
  2: { value: 90, label: "High" },
};
